# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "priorities", :force => true do |t|
    t.column "name", :string
  end

  create_table "quadrants", :force => true do |t|
    t.column "name", :string
  end

  create_table "tasks", :force => true do |t|
    t.column "title",       :string
    t.column "priority_id", :integer
    t.column "order",       :integer
    t.column "quadrant_id", :integer
    t.column "due_date",    :date
    t.column "created_at",  :datetime
    t.column "updateed_at", :datetime
  end

end
